### ISSUE TITLE
The plugin is not working

### ISSUE THREAD

**Issue by poguinha** [SirMonkeyBoy/Crossplay#1]
When i start my server with Tshock, the program can't read or use the plugin

**Comment by SirMonkeyBoy** [comment]
Are you using tshock 5.1.2 and the crossplay.dll

**Comment by Toopyaaaa** [comment]
it didnt work for me either. it says the plugin is outdated

**Comment by Toopyaaaa** [comment]
I am using tshock 5.1.2 and your crossplay plugin but it says yhe plugin is outdated

**Comment by SirMonkeyBoy** [comment]
did you have the outdated plugin installed

**Comment by SirMonkeyBoy** [comment]
And can anyone send the error logs I haven't been able to make it fail

**Comment by SirMonkeyBoy** [comment]
Money lover has updated their cross play plugin https://github.com/Moneylover3246/Crossplay use that it should work
